name: zoo_lints
description: Recommended lints for Flutter apps, packages, and plugins to
  encourage good coding practices.
version: 1.0.2
repository: https://github.com/zoocityboy/zoo_lints
issue_tracker: https://github.com/zoocityboy/zoo_lints/issues
homepage: https://github.com/zoocityboy/zoo_lints
documentation: https://github.com/zoocityboy/zoo_lints

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  very_good_analysis: ">=3.0.0 <=3.1.0"
