name: zoo_lints
description: Recommended lints for Flutter apps, packages, and plugins to
  encourage good coding practices.
version: 3.1.0+1
repository: https://github.com/zoocityboy/zoo_lints
issue_tracker: https://github.com/zoocityboy/zoo_lints/issues
homepage: https://github.com/zoocityboy/zoo_lints
documentation: https://github.com/zoocityboy/zoo_lints
topics: [lints, analyzer, analysis, zoo]

screenshots:
  - description: Cover
    path: assets/zoo_lints.png

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  very_good_analysis: ^5.1.0
